/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/credit`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/crop` | `/crop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/detect` | `/detect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/listing`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/order`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/orders`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/payment`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/credit`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/crop` | `/crop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/detect` | `/detect`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/listing`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/order`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/credit${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/crop${`?${string}` | `#${string}` | ''}` | `/crop${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/detect${`?${string}` | `#${string}` | ''}` | `/detect${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/marketplace/create${`?${string}` | `#${string}` | ''}` | `/marketplace${`?${string}` | `#${string}` | ''}` | `/marketplace/listing${`?${string}` | `#${string}` | ''}` | `/marketplace/order${`?${string}` | `#${string}` | ''}` | `/marketplace/orders${`?${string}` | `#${string}` | ''}` | `/marketplace/payment${`?${string}` | `#${string}` | ''}` | `/marketplace/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/credit`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/crop` | `/crop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/detect` | `/detect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/listing`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/order`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/orders`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/payment`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/register`; params?: Router.UnknownInputParams; };
    }
  }
}
